# L'importation des libraries

In [1]:
import pandas as pd
import numpy as np
from sklearn.decomposition import PCA    

# l'importation des donnees a partir d'un fichier Excel

In [2]:
data = pd.read_excel('dataset_acp.xlsx')

# Extraction des variables à partir des données importées 

In [3]:
X = data[['X1', 'X2', 'X3']]

In [4]:
X


X1  X2  X3
0   2   4   2
1   4   6   1
2   6  -1   3
3   3   5  -1

# La standardisation des données


In [5]:
X_std = (X - X.mean(axis=0)) / X.std(axis=0)

In [6]:
X_std


X1        X2        X3
0 -1.024695  0.160817  0.439155
1  0.146385  0.804084 -0.146385
2  1.317465 -1.447352  1.024695
3 -0.439155  0.482451 -1.317465

# Création d'une instance de la classe PCA

In [7]:
pca = PCA(n_components=3)

# L'application de l'algorithme de l'ACP sur les données centrées et réduites (standardisées)


In [8]:
pca.fit(X_std)

PCA(n_components=3)

# Extraction des composantes principales et leurs variances expliquées

In [9]:
components = pca.components_
explained_variances = pca.explained_variance_ratio_

# Affichage des composantes principales et leurs variances expliquées


In [10]:
print("Composantes principales:")
print(components)
print("\nVariances expliquées:")
print(explained_variances)

Composantes principales:
[[ 5.54845442e-01 -6.19913761e-01  5.54845442e-01]
 [-7.07106781e-01  1.02162388e-16  7.07106781e-01]
 [ 4.38345224e-01  7.84669949e-01  4.38345224e-01]]

Variances expliquées:
[0.76410219 0.17142857 0.06446923]


## Commentaire : 

c'est claire que la première composante sera prise en considération car sa variance expliqueé est très élevée(=77%)